source "https://supermarket.chef.io"

cookbook 'chef-dk'
cookbook 'git'
cookbook 'heroku-toolbelt', '~> 0.1.0'
cookbook 'iptables'
cookbook 'man'
cookbook 'mercurial'
cookbook 'mongodb'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'php'
cookbook 'php-fpm'
cookbook 'screen'
cookbook 'selinux'
cookbook 'sqlite'
cookbook 'subversion', '~> 1.3.0'
cookbook 'tmux'
cookbook 'vim'
cookbook 'vsftpd'
cookbook 'zsh'
