include_recipe "../cookbooks/essential/apt.rb"
include_recipe "../cookbooks/essential/user.rb"
include_recipe "../cookbooks/essential/swap.rb"
include_recipe "../cookbooks/essential/build-essential.rb"
include_recipe "../cookbooks/essential/default.rb"
include_recipe "../cookbooks/essential/directories.rb"
