version: 2
jobs:
  build:
    machie: true
    working_directory: ~/circleci
    docker:
      - image: ubuntu:xenial
    steps:
      - run: cat /etc/lsb-release
      - run: uname -a
      - run: env | sort

      #- restore_cache:
      #-   key: anyenv-cache

      - run: apt-get update -y
      - run: apt-get install -y sudo
      - run: apt-get install -y ruby2.3 ruby2.3-dev git make
      - run: gem2.3 i bundler --no-rdoc --no-ri

      - checkout
      - run: make
      - run: make circle

      #- save_cache:
      #-   key: anyenv-cache
      #-   paths:
      #-     - /usr/local/anyenv
      #-     - /usr/local/etc/anyenvrc
